# Generated by Django 2.2.7 on 2019-11-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ca_crt', models.TextField()),
                ('ca_key', models.TextField()),
                ('address_prefix', models.GenericIPAddressField(protocol='ipv4')),
                ('cidr_bits', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.GenericIPAddressField(protocol='ipv4')),
                ('port', models.PositiveIntegerField(default=4242)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.GenericIPAddressField(protocol='ipv4')),
                ('member_crt', models.TextField()),
                ('member_key', models.TextField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_lighthouse', models.BooleanField(blank=True, default=False)),
                ('nebula_port', models.PositiveIntegerField(default=4242)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='nebula.Network')),
                ('static_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nebula.StaticHost')),
            ],
        ),
    ]
