# Generated by Django 2.2.7 on 2019-11-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDeploymentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('join_template', models.TextField(blank=True)),
                ('update_template', models.TextField(blank=True)),
                ('leave_template', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='deployment_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nebula.MemberDeploymentTemplate'),
        ),
    ]
