# Generated by Django 2.2.7 on 2019-11-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebula', '0002_auto_20191127_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('key', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='ssh_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nebula.SSHCredentials'),
        ),
    ]
