# Generated by Django 2.2.7 on 2019-11-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebula', '0004_auto_20191129_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberDeploymentTemplate',
        ),
    ]
